project:
  type: website
  output-dir: "."

website:
  title: "Christopher Taratko"
  navbar:
    pinned: true
    left:
      - text: Project
        href: project.qmd
      #- text: Portfolio Development
      #  href: PortfolioDevelopment.qmd
      - text: Blog
        href: blog-listing.qmd
      - text: Lab Review
        href: Analytics200Review.qmd
      - text: 210 Projects List
        menu:
        - text: 210 Project 1
          href: DANL210_Project.qmd
  page-footer: 
    center: "Powered with GitHub and Quarto<br>© Christopher Taratko, 2023"

format:
  html:
    theme: 
      light: flatly
      dark: darkly
    mainfont: system-ui; 
    highlight-style: atom-one
    css: styles.css
    toc: false
    include-after-body: target_blank.html
    
